import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { AuthenticationProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthenticationProvider>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Header />

          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            {children}
          </div>
        </div>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
